version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/react-tabllist
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-package
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test-stylelint
          command: npm run lint
      - run:
          name: run-unit-test-and-uploading-reports
          command: npm run test
      - run:
          name: chmod
          command: chmod +x build/scripts/pushDemo.sh
      - run:
          name: build-demo
          command: build/scripts/pushDemo.sh
